import { DEFAULT_SETTINGS, WorksheetBlock, WorksheetSettings } from "@/types/worksheet";

const baseVisibility = { visibility: "both" as const };

export const printFixtureTitle = "Print Fixture";

export const printFixtureSettings: WorksheetSettings = {
  ...DEFAULT_SETTINGS,
  brand: "edoomio",
  showHeader: true,
  showFooter: true,
  fontSize: 12.5,
};

export const printFixtureBlocks: WorksheetBlock[] = [
  {
    id: "fixture-heading-1",
    type: "heading",
    level: 1,
    content: "Print fixture for real viewer output",
    ...baseVisibility,
  },
  {
    id: "fixture-meta",
    type: "text",
    textStyle: "metadaten",
    content: "<p>Debug route using the real print viewer DOM and live print CSS.</p>",
    ...baseVisibility,
  },
  {
    id: "fixture-standard",
    type: "text",
    textStyle: "standard",
    content: "<p>This fixture is the new transfer point between styling work and the Puppeteer output path.</p><ul><li>Same React render tree</li><li>Same print mode</li><li>Same global print styles</li></ul>",
    ...baseVisibility,
  },
  {
    id: "fixture-example",
    type: "text",
    textStyle: "example",
    content: "<p><strong>Example:</strong> Lara arrives at school early and checks the timetable before class starts.</p>",
    comment: "Classic example box rendered by the real viewer.",
    ...baseVisibility,
  },
  {
    id: "fixture-example-standard",
    type: "text",
    textStyle: "example-standard",
    content: "<p><strong>Example standard:</strong> Write one short sentence about your morning routine.</p>",
    comment: "Used to compare the split example layout in print.",
    ...baseVisibility,
  },
  {
    id: "fixture-example-improved",
    type: "text",
    textStyle: "example-improved",
    content: "<p><strong>Example improved:</strong> Add one extra detail so the second line wraps and exposes spacing changes.</p>",
    comment: "Improved example variant with multiline content.",
    ...baseVisibility,
  },
  {
    id: "fixture-hinweis",
    type: "text",
    textStyle: "hinweis",
    content: "<p>Hint boxes should align from the real viewer structure, not from hand-written debug markup.</p>",
    ...baseVisibility,
  },
  {
    id: "fixture-hinweis-important",
    type: "text",
    textStyle: "hinweis-wichtig",
    content: "<p>Important hint: verify icon alignment, gap, border radius and print-safe fills against the real route.</p>",
    ...baseVisibility,
  },
  {
    id: "fixture-hinweis-alert",
    type: "text",
    textStyle: "hinweis-alarm",
    content: "<p>Alert variant to check the last tuned spacing and padding behavior.</p>",
    ...baseVisibility,
  },
  {
    id: "fixture-lernziel",
    type: "text",
    textStyle: "lernziel",
    content: "<p>Lernziel: compare the debug fixture against the real print route without duplicating structure.</p>",
    ...baseVisibility,
  },
  {
    id: "fixture-kompetenzziele",
    type: "text",
    textStyle: "kompetenzziele",
    content: "<p>Kompetenzziele:</p><ul><li>Identify print regressions faster</li><li>Review the actual HTML structure</li></ul>",
    ...baseVisibility,
  },
  {
    id: "fixture-handlungsziele",
    type: "text",
    textStyle: "handlungsziele",
    content: "<p>Handlungsziele:</p><ul><li>Open the fixture route</li><li>Generate the PDF</li><li>Compare the result</li></ul>",
    ...baseVisibility,
  },
  {
    id: "fixture-rows",
    type: "text",
    textStyle: "rows",
    content: "<p>Rows style for matching line-height and separator handling in print.</p>",
    ...baseVisibility,
  },
  {
    id: "fixture-heading-2",
    type: "heading",
    level: 2,
    content: "Interactive blocks",
    ...baseVisibility,
  },
  {
    id: "fixture-multiple-choice",
    type: "multiple-choice",
    instruction: "Choose the correct answer.",
    question: "Which route should own the production print HTML?",
    allowMultiple: false,
    options: [
      { id: "fixture-mc-1", text: "The real print viewer route", isCorrect: true },
      { id: "fixture-mc-2", text: "A separate static debug HTML file", isCorrect: false },
      { id: "fixture-mc-3", text: "The PDF API response body", isCorrect: false },
    ],
    ...baseVisibility,
  },
  {
    id: "fixture-true-false",
    type: "true-false-matrix",
    instruction: "Mark each statement as true or false.",
    trueLabel: "True",
    falseLabel: "False",
    statements: [
      { id: "fixture-tf-1", text: "The fixture route renders through WorksheetViewer.", correctAnswer: true },
      { id: "fixture-tf-2", text: "The fixture depends on Prisma data.", correctAnswer: false },
      { id: "fixture-tf-3", text: "Solutions mode helps verify final control styling.", correctAnswer: true },
    ],
    ...baseVisibility,
  },
  {
    id: "fixture-open-response",
    type: "open-response",
    question: "Describe the visual differences you still see between the debug file and this real print fixture.",
    lines: 4,
    ...baseVisibility,
  },
  {
    id: "fixture-word-bank",
    type: "word-bank",
    words: ["alignment", "padding", "border", "radius", "print", "fixture"],
    ...baseVisibility,
  },
  {
    id: "fixture-article-training",
    type: "article-training",
    instruction: "Choose the correct article.",
    showWritingLine: true,
    items: [
      { id: "fixture-at-1", text: "Tisch", correctArticle: "der" },
      { id: "fixture-at-2", text: "Lampe", correctArticle: "die" },
      { id: "fixture-at-3", text: "Buch", correctArticle: "das" },
    ],
    ...baseVisibility,
  },
  {
    id: "fixture-heading-3",
    type: "heading",
    level: 2,
    content: "Recently tuned content blocks",
    ...baseVisibility,
  },
  {
    id: "fixture-numbered-items",
    type: "numbered-items",
    startNumber: 1,
    borderRadius: 4,
    items: [
      { id: "fixture-ni-1", content: "<p>Number badges should stay visually stable even when borders get thicker.</p>" },
      { id: "fixture-ni-2", content: "<p>This item deliberately wraps onto a second line so vertical alignment stays visible in print.</p>" },
      { id: "fixture-ni-3", content: "<p>Compare spacing, divider rhythm and badge width against the old debug sample.</p>" },
    ],
    ...baseVisibility,
  },
  {
    id: "fixture-checklist",
    type: "checklist",
    items: [
      { id: "fixture-cl-1", content: "<p>Badge before checkbox</p>" },
      { id: "fixture-cl-2", content: "<p>Checkbox geometry matches the true or false matrix</p>" },
      { id: "fixture-cl-3", content: "<p>Text start aligns with the numbered item comparison row</p>" },
    ],
    ...baseVisibility,
  },
  {
    id: "fixture-text-comparison",
    type: "text-comparison",
    leftContent: "<p><strong>Current debug process</strong></p><p>Fast for visual tweaking, but easy to drift away from production DOM.</p>",
    rightContent: "<p><strong>Fixture route process</strong></p><p>Slower to set up once, then safer because Puppeteer and the browser inspect the same structure.</p>",
    ...baseVisibility,
  },
  {
    id: "fixture-dos-donts",
    type: "dos-and-donts",
    layout: "horizontal",
    showTitles: true,
    dosTitle: "Do",
    dontsTitle: "Do not",
    dos: [
      { id: "fixture-do-1", text: "Tune print styles against the real viewer output and compare against the same route in the browser." },
      { id: "fixture-do-2", text: "Use one fixture route for browser and PDF checks so spacing and structure regressions stay visible." },
    ],
    donts: [
      { id: "fixture-dont-1", text: "Copy HTML by hand into a separate debug file and expect long-term parity." },
      { id: "fixture-dont-2", text: "Validate only CSS when the DOM structure, row dividers and list markers also matter." },
    ],
    ...baseVisibility,
  },
  {
    id: "fixture-snippet",
    type: "text-snippet",
    content: "<p>Use this route when adjusting line-height, list rhythm and compact print snippets.</p>",
    ...baseVisibility,
  },
  {
    id: "fixture-email",
    type: "email-skeleton",
    from: "nora@example.com",
    to: "kurs@example.com",
    subject: "Print fixture check",
    body: "<p>Hello team,</p><p>Please compare the fixture PDF with the browser print preview and note any spacing differences.</p><p>Best regards,<br/>Nora</p>",
    emailStyle: "none",
    attachments: [
      { id: "fixture-attachment-1", name: "comparison-notes.pdf" },
    ],
    ...baseVisibility,
  },
  {
    id: "fixture-table",
    type: "table",
    tableStyle: "default",
    content: "<table><tbody><tr><th><p>Area</p></th><th><p>Check</p></th><th><p>Status</p></th></tr><tr><td><p>Hint boxes</p></td><td><p>Icon offset and text gap</p></td><td><p>Review</p></td></tr><tr><td><p>Controls</p></td><td><p>20px geometry with correct success fill</p></td><td><p>Review</p></td></tr><tr><td><p>Lists</p></td><td><p>Bullet style and row dividers</p></td><td><p>Review</p></td></tr></tbody></table>",
    ...baseVisibility,
  },
  {
    id: "fixture-schedule",
    type: "schedule",
    showDate: true,
    showRoom: true,
    showHeader: true,
    items: [
      { id: "fixture-sc-1", date: "2026-04-07", start: "08:30", end: "09:15", room: "A101", title: "Grammatik: Perfekt", description: "Regelmäßige und unregelmäßige Verben" },
      { id: "fixture-sc-2", date: "2026-04-07", start: "09:30", end: "10:15", room: "A101", title: "Hören & Sprechen", description: "Dialoge aus dem Alltag" },
      { id: "fixture-sc-3", date: "2026-04-08", start: "08:30", end: "09:15", room: "B203", title: "Lesen & Verstehen", description: "" },
      { id: "fixture-sc-4", date: "2026-04-08", start: "09:30", end: "10:15", room: "B203", title: "Schreiben: E-Mail", description: "Formelle und informelle Schreibweise" },
    ],
    ...baseVisibility,
  },
  {
    id: "fixture-website",
    type: "website",
    title: "Useful websites",
    level: 2,
    items: [
      {
        id: "fixture-web-1",
        title: "Arbeitsblatt",
        url: "https://arbeitsblatt.ch",
        category: "Platform",
        description: "Worksheet publishing and editor workflows used for browser and print verification.",
        image: "/logo/arbeitsblatt_logo_icon.svg",
      },
      {
        id: "fixture-web-2",
        title: "Frauenfeld",
        url: "https://www.frauenfeld.ch",
        category: "Reference",
        description: "City reference page used here to verify multi-line titles, categories and linked descriptions.",
        image: "/logo/logo-stadt-frauenfeld.svg",
      },
    ],
    ...baseVisibility,
  },
  {
    id: "fixture-accordion",
    type: "accordion",
    showNumbers: true,
    items: [
      {
        id: "fixture-acc-1",
        title: "Why this route matters",
        children: [
          {
            id: "fixture-acc-1-text",
            type: "text",
            textStyle: "standard",
            content: "<p>The fixture uses the production viewer renderer, so HTML structure and print CSS can be checked together.</p>",
            ...baseVisibility,
          },
        ],
      },
    ],
    ...baseVisibility,
  },
];